### ISSUE TITLE
dump_db problem

### ISSUE THREAD

**Issue by Alexisxsy** [studio-ousia/wikipedia2vec#8]
Hi all, 

I have tried to use this project to train a new embedding for entities and words. However, after running  **wikipedia2vec build_dump_db DUMP_FILE OUT_FILE** 
There occur some problems.
1. The OUT_FILE is about 93.1GB, not 15GB as described.
2. If I run **wikipedia2vec build_phrase_dictionary DUMP_DB_FILE OUT_FILE** on Windows Server 2012, there will pop out a lot of windows warning "python has stopped working".

My python version is 3.6 and I haven't install any BLAS library

I am wondering if there are any problems?

Thank you very much!

**Comment by Alexisxsy** [comment]
Hi Yamada, 
Thank you for your reply. I download the Wikipedia dump from https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2

**Comment by ikuyamada** [comment]
Thank you for your prompt reply. The Dump DB is approximately 15GB based on the latest dump in our Ubuntu-based server, the problem is likely related to your environment. We will investigate your problem further.

**Comment by ikuyamada** [comment]
We added experimental support for Windows. Please test it using the latest version (v0.1.15) available at PyPI.

**Comment by ypc-stu** [comment]
Hello,@ikuyamada,
          I downloaded the codes to train a new embedding for entities and words ,and also I downloaded the Wikipedia dump from https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2, Finally,I want to get new embedding for entities and words  in glove from ,not word2vec from. If I want to run this codes, How should I enter commands?
look forward to your replies,thanks!

**Comment by ikuyamada** [comment]
@ypc-stu Please use the `train` command described here: https://wikipedia2vec.github.io/wikipedia2vec/commands/

**Comment by ypc-stu** [comment]
I see it,thank you for your prompt reply!
